version: "3.8"
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: grocary
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/grocary
      PORT: 3000
      JWT_SECRET: verystrongsecret
      JWT_EXPIRES_IN: 1h
      BCRYPT_SALT_ROUNDS: "10"
      CORS_ALLOWED_ORIGINS: "*"
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
volumes:
  db-data:
