name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install
        run: npm i --force
      - name: Build
        run: npm run build
      # Optionally build and push Docker image (commented placeholders)
      #- name: Build Docker image
      #  run: docker build -t ${{ secrets.DOCKER_REPO }}:${{ github.sha }} .
      # - name: Push Docker image
      #   uses: docker/build-push-action@v3
      #   with:
      #     push: true
      #     tags: ${{ secrets.DOCKER_REPO }}:latest
